---
title: "Filter genotypes"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

**Started**: Alexey Larionov, 10 July 20  
**last updated**: Rofaida Desoki, 13 July 2020

# Summary

- Set genotype to NA if individual genotype depth DP < 10 or individual genotype quality GQ < 20  
- Check that call rate remains > 0.85 for all variants after the genotypes filtering  

<style>
pre{
  overflow-x: auto;
}
pre code{
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r echo=F}

options(width=999)

```

# Start section

```{r}

# Time
Sys.time()

# Clean up
rm(list=ls())
graphics.off()

# Options
options(stringsAsFactors = F)

# Working folders
base_folder <- "/home/rdesoki/re_gecip/inherited_cancer_predisposition/rofaida/Rproject"

scripts_folder <- file.path(base_folder,"scripts","s08_consolidate_dataset")
setwd(scripts_folder)

data_folder <- file.path(base_folder,"data","s08_consolidate_dataset")

```

# Read data

```{r}

load(file.path(data_folder,"s01_import_vcf_to_R.RData"))

ls()

full.vcfr

dim(header.df)
dim(variants.df)

dim(full_dp.mx)
dim(full_gq.mx)
dim(full_gt.mx)

```

# Filter genotype data

```{r}

# Initial count of missed genotypes
sum(is.na(full_gt.mx))

# Count of genotypes with low depth
sum(full_dp.mx < 10)

# Count genotypes with low quality
sum(full_gq.mx < 20)

# Remove genotypes with low depth or quality
NA -> full_gt.mx[full_dp.mx < 10]
NA -> full_gt.mx[full_gq.mx < 20]

# Check number of missed genotypes
sum(is.na(full_gt.mx))

```

# Preliminary (!!) check of the variant call rates

```{r}

var_call_rates <- apply(full_gt.mx, 1, function(x){sum(!is.na(x))/length(x)})
hist(var_call_rates)
min(var_call_rates)

rm(var_call_rates)

```

# Save results

```{r}

save.image(file.path(data_folder,"s02_filter_genotypes.RData"))

```

# Final section

```{r}

ls()
sessionInfo()
Sys.time()

```
